# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ata_piix" "ohci_pci" "ehci_pci" "ahci" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-5430def4-31f6-4e1b-b721-96b1d960e00e";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-5430def4-31f6-4e1b-b721-96b1d960e00e".device = "/dev/disk/by-uuid/5430def4-31f6-4e1b-b721-96b1d960e00e";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A59D-EB0D";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [{
    device = "/dev/sdb1";
  }];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  virtualisation.virtualbox.guest.enable = true;
}
